name: Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql user: test
        postgresql password: password
    - name: Set up Redis
      uses: zhulik/redis-action@1.1.0
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build app
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rails db:setup RAILS_ENV=test
      env:
        DATABASE_URL: 'postgres://test:password@localhost/profiler_test'
    - name: Run specs
      run: |
        bundle exec rspec
      env:
        SEND_EMAIL_DOMAIN: 'lvh.me'
        DATABASE_URL: 'postgres://test:password@localhost/profiler_test'
    - name: Merge to deploy branch
      uses: devmasx/merge-branch@v1.1.0
      with:
        type: now
        target_branch: 'deploy'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
  